In [1]:
# array : array is a part of data structures and collection in pyhton 
# array is collection of multple data stored in a single variables there we can used array 
# in python array used as list []
emp=["brijesh","rajesh",123]
print(emp)

['brijesh', 'rajesh', 123]


In [2]:
emp=["brijesh","rajesh",123]
print(type(emp))

<class 'list'>


In [4]:
# python is not support built in array data type 
# python support array using numpy library 
# python support array via numpy array 
import numpy as np
res=np.array([1,2,3,4,5,6])
print(res)
print(type(res))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [7]:
# multidimentional array 
import numpy as np
res=np.array([[1,2],[3,4]])
print(res)

[[1 2]
 [3 4]]


In [9]:
import numpy as np
res=np.array([[1,2],[3,4],[5,6],[7,8]])
print(res)
print(type(res))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
res=np.array([1,2,3,4])
print(res*2)
print(type(res))

[2 4 6 8]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
res=np.array([1,2,3,4])
print(res-2)
print(type(res))

[-1  0  1  2]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
res=np.array([1,2,3,4])
print(res/2)
print(type(res))

[0.5 1.  1.5 2. ]
<class 'numpy.ndarray'>


In [14]:
# accesssing array elements 
# import numpy as np
# res=np.array(["brijesh","devanshu","rajesh"])
# print(res[2])


import numpy as np
res=np.array(["brijesh","devanshu","rajesh"])
print(res[1])


devanshu


In [22]:
# array append ...
# import numpy as np
# res=np.array(["brijesh","devanshu","rajesh"])
# res1 = np.append(res, "jinali")
# print(res1)


import numpy as np
res=np.array(["brijesh","devanshu","rajesh"])
print(np.append(res,["kumar","rajesh"]))


['brijesh' 'devanshu' 'rajesh' 'kumar' 'rajesh']


In [19]:
# loop 
import numpy as np
res=np.array(["brijesh","devanshu","rajesh"])
for i in res:
    print(i)

brijesh
devanshu
rajesh


In [20]:
# loop 
import numpy as np
res=np.array(["brijesh","devanshu","rajesh","brijesh","rajesh","devanshu"])
for i in res:
    print(i)

brijesh
devanshu
rajesh
brijesh
rajesh
devanshu


In [30]:
# add new element n array insert()
# import numpy as np 
# data=np.array([1,2,3,4,5,6,7,8,9])
# print(data)

import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9])
data = np.insert(data, 9,6)
print(*data)

1 2 3 4 5 6 7 8 9 6


In [31]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9])
data = np.insert(data, 9,6)
print(*data)

1 2 3 4 5 6 7 8 9 6


In [39]:
# removed element 
# import numpy as np
# data = np.array([1,2,3,4,5,6,7,8,9])
# data = np.delete(data, np.where(data == 8))
# print(data)

# import numpy as np
# data = np.array([1,2,3,4,5,6,7,8,9])
# data = np.delete(data, np.where(data == 9))
# print(data)


# import numpy as np
# data = np.array([1,2,3,4,5,6,7,8,9])
# data = np.delete(data,8)
# print(data)

import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9])
data = np.delete(data,7)
print(data)

[1 2 3 4 5 6 7 9]


In [41]:
# reverse any array 
data = np.array([1,2,3,4,5,6,7,8,9])
data = data[::-1]
print(data)

[9 8 7 6 5 4 3 2 1]
